name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

# build-qemu:
#
#   runs-on: ubuntu-latest
#
#   steps:
#   - uses: actions/checkout@v4
#   - name: Install deps
#     run: |
#       sudo apt update && sudo apt upgrade && sudo apt install ninja-build -y
#       wget https://apt.llvm.org/llvm.sh
#       chmod +x llvm.sh
#       sudo ./llvm.sh 18 all
#   - name: Build
#     run: cargo build --verbose --features qemu_x86_64
